linuxdeepin/deepin-camera

src/src/videowidget.cpp

fix: 解决申威平台连续点击录像按钮卡死的问题

---

debian/deepin-camera.postinst

Description: 等保三根目录删除temp目录
Log: 等保三根目录删除temp目录
Bug: https://pms.uniontech.com/bug-view-115465.html

fix: 等保三根目录删除temp目录

---

src/src/gridline.cpp
src/src/mainwindow.cpp
src/src/majorimageprocessingthread.cpp
src/src/majorimageprocessingthread.h
src/src/takephotosettingareawidget.cpp
src/src/takephotosettingareawidget.h
src/src/videowidget.cpp
src/src/videowidget.h

重绘构图网格时未对画面区域尺寸为零时做处理
Log: 构图网格问题修复
Bug: https://pms.uniontech.com/bug-view-117771.html

fix: 修复延时拍照构图网格线会延伸到画面外

---

src/src/videowidget.cpp

Description: 解决开启十字网格连拍时,网格线会延伸到窗口边缘的问题
Log: 解决开启十字网格连拍时,网格线会延伸到窗口边缘的问题
Bug: https://pms.uniontech.com/zentao/bug-view-117771.html

fix: 解决开启十字网格连拍时,网格线会延伸到窗口边缘的问题

---

src/src/videowidget.cpp

Description: 解决网格线显示错误的问题
Log: 解决网格线显示错误的问题

fix: 解决网格线显示错误的问题

---

src/src/camera.cpp

Description: 解决arm平台ut报错问题
Log: 解决arm平台ut报错问题

fix: 解决arm平台ut报错问题

---

debian/control
src/CMakeLists.txt
src/main.cpp
src/src/Settings.cpp
src/src/audioprocessingthread.cpp
src/src/audioprocessingthread.h
src/src/basepub/datamanager.cpp
src/src/basepub/datamanager.h
src/src/gstvideowriter.cpp
src/src/gstvideowriter.h
src/src/imageitem.cpp
src/src/mainwindow.cpp
src/src/majorimageprocessingthread.cpp
src/src/majorimageprocessingthread.h
src/src/videowidget.cpp
src/src/videowidget.h
tests/CMakeLists.txt
tests/CameraTest.cpp
tests/stub/stub_function.cpp
tests/stub/stub_function.h

Description: 使用GStreamer方案实现录像功能
Log: 使用GStreamer方案实现录像功能

fix: 使用GStreamer方案实现录像功能

---

src/src/majorimageprocessingthread.h
tests/GStreamerTest.cpp
tests/GStreamerTest.h
tests/stub/stub_function.cpp
tests/stub/stub_function.h

Description: GStreamer方案添加UT单元测试
Log: GStreamer方案添加UT单元测试

fix: GStreamer方案添加UT单元测试

---

libcam/libcam_encoder/encoder.c
libcam/libcam_v4l2core/frame_decoder.c
libcam/libcam_v4l2core/v4l2_core.c
src/main.cpp
src/src/gstvideowriter.cpp
src/src/gstvideowriter.h
src/src/mainwindow.cpp
src/src/majorimageprocessingthread.cpp
src/src/majorimageprocessingthread.h
src/src/videowidget.cpp

Description: 非FFmpeg环境下没有libavcodec等库，所以直接使用v4l2的jpg格式帧数据显示相机画面
Log: 解决非FFmpeg环境下，启动相机失败的问题

fix: 解决非FFmpeg环境下，启动相机失败的问题

---

src/src/audioprocessingthread.cpp

Description: 解决GStreamer音频采集内存泄露问题
Log: 解决GStreamer音频采集内存泄露问题

fix: 解决GStreamer音频采集内存泄露问题

---

src/src/audioprocessingthread.cpp
src/src/gstvideowriter.cpp

Description: 解决内存泄漏问题
Log: 解决内存泄露问题

fix: 解决内存泄露问题

---

src/src/gstvideowriter.cpp
src/src/gstvideowriter.h

Description: 修改vp8编码参数，巨量提升各平台vp8编码效率
Log: amd/arm/mips平台，GStreamer录像性能优化

fix: amd/arm/mips平台，GStreamer录像性能优化

---

src/src/mainwindow.cpp
src/src/takephotosettingareawidget.cpp
src/src/takephotosettingareawidget.h

修改窗口最小尺寸，顺便改了滤镜布局
Task: https://pms.uniontech.com/task-view-122527.html
Log: 完成部分需求

feat: 修改窗口最小尺寸

---

src/src/mainwindow.cpp
src/src/takephotosettingareawidget.cpp

修改窗口默认尺寸
Bug: https://pms.uniontech.com/bug-view-130687.html, https://pms.uniontech.com/bug-view-130819.html
Log: 修复部分已知问题

fix: 窗口默认尺寸错误

---

src/src/takephotosettingareawidget.cpp

修复滚动条跟随焦点进行移动
Bug: https://pms.uniontech.com/bug-view-130643.html
Log: 修复部分已知问题

fix: 修复滚动条未跟随焦点问题

---

libcam/libcam/camview.c
libcam/libcam_encoder/mp4.c
libcam/libcam_encoder/mp4.h
libcam/libcam_encoder/muxer.c
libcam/libcam_v4l2core/gui.c
src/assets/resource/settings.json
src/src/Settings.cpp
src/src/Settings.h
src/src/imageitem.cpp
src/src/mainwindow.cpp
src/src/videowidget.cpp
src/src/videowidget.h

增加mp4录制格式
Task: https://pms.uniontech.com/task-view-122535.html
Log: 增加mp4录制格式

feat: 增加mp4录制格式

---

src/src/Settings.cpp
src/src/videowidget.cpp

修复gstreamer下可以录制mp4
Bug: https://pms.uniontech.com/bug-view-134749.html
Log: 修复部分已知问题

fix: 修复gstreamer下可以录制mp4

---

src/src/majorimageprocessingthread.cpp
src/src/majorimageprocessingthread.h

fix: 修复兆芯拖动闪退问题

---

libcam/libcam_v4l2core/v4l2_formats.c
src/assets/resource/settings.json
src/src/videowidget.cpp

修改闪光灯默认关闭
Bug: https://pms.uniontech.com/bug-view-132743.html
Log: 修复部分已知问题

fix: 修改闪光灯默认

---

src/CMakeLists.txt
src/main.cpp
src/src/gstvideowriter.cpp
src/src/gstvideowriter.h
src/src/videowidget.cpp

动态加载gstreamer
Log: 动态加载gstreamer

fix: 动态加载gstreamer

---

debian/control
src/src/mainwindow.cpp

修改control文件依赖
Log: 修改control文件依赖

fix: 修改control文件依赖

---

libcam/libcam_encoder/mp4.c

按照真实时间填写帧pts
Bug: https://pms.uniontech.com/bug-view-138379.html
Log: 修复部分已知问题

fix: 修复社区版上播放快速问题

---

src/src/mainwindow.cpp

修复滤镜名称未隐藏问题
Bug: https://pms.uniontech.com/bug-view-138271.html
Log: 修复部分已知问题

fix: 修复滤镜名称未隐藏问题

---

src/src/videowidget.cpp

在维语环境下增加控件宽度
Bug: https://pms.uniontech.com/bug-view-114319.html
Log: 修复部分已知问题

fix: 修复维语下显示不全问题

---

src/src/LPF_V4L2.c
src/src/camera.cpp

修复cppcheck检查错误
Log: 修复cppcheck检查错误

fix: 修复cppcheck检查错误

---

debian/rules
libcam/libcam_audio/audio_portaudio.c
libcam/libcam_encoder/encoder.c
src/src/basepub/load_libs.c
src/src/basepub/load_libs.h

修复ffmpeg4.4 无声音问题
Log: 修复ffmpeg4.4 无声音问题
/review 
@wyu71

fix: 修复ffmpeg4.4 无声音问题

---

debian/changelog
src/src/eventlogutils.cpp
src/src/eventlogutils.h
src/src/mainwindow.cpp
src/src/videowidget.cpp

feat: 数据埋点功能实现

---

tests/CMakeLists.txt

Fix unit test compilation failure
Log: bug fix
Bug: https://pms.uniontech.com/bug-view-148719.html

fix: unit test compilation failure

---

src/src/mainwindow.cpp
src/src/videowidget.cpp

暂时屏蔽除应用启动外的数据埋点
Log: 屏蔽除应用启动外的数据埋点

fix: 屏蔽数据埋点

---

src/src/mainwindow.cpp
src/src/videowidget.cpp

修复应用启动是否连接摄像头错误;录像结束时长错误
Log: 修复应用启动是否连接摄像头错误;录像结束时长错误
Bug: https://pms.uniontech.com/bug-view-152149.html
https://pms.uniontech.com/bug-view-152153.html

fix: 埋点bug修复

---

src/src/eventlogutils.h

fix: 修改启动tid

---

libcam/libcam_encoder/mp4.c

klv录制mp4视频，播放时出现花屏
Log: 修复klv录制mp4视频花屏
Bug: https://pms.uniontech.com/bug-view-154693.html

fix: klv录制视频花屏

---

src/src/majorimageprocessingthread.cpp

使用QImage保存照片，修复特殊分辨率拍照乱码问题
Log: 使用QImage保存照片
Bug: https://pms.uniontech.com/bug-view-154183.html

fix: 使用QImage保存照片

---

src/src/majorimageprocessingthread.cpp

修复插入新的摄像头异常崩溃问题
Log: 修复插入新的摄像头异常崩溃问题
Bug: https://pms.uniontech.com/bug-view-155719.html
/review 
@myk1343 @feeengli

fix: 修复插入新的摄像头异常崩溃问题

---

src/src/previewopenglwidget.cpp

修复甜甜圈摄像头预览画面卡顿问题
Log: 修复甜甜圈摄像头预览画面卡顿问题
Bug: https://pms.uniontech.com/bug-view-154541.html

fix: 修复甜甜圈摄像头预览画面卡顿问题

---

src/src/majorimageprocessingthread.cpp

fix: 内存泄露修复

---

src/CMakeLists.txt

Log: use GNUInstallDirs in CmakeLists
https://github.com/linuxdeepin/developer-center/issues/3167

chore: use GNUInstallDirs in CmakeLists

---

LICENSE
README.md
README.zh_CN.md
libcam/libcam_encoder/mp4.c
libcam/libcam_encoder/mp4.h
src/src/accessibility/acobjectlist.h
src/src/accessible/accessiblefunctions.h
src/src/accessible/accessiblelist.h
src/src/audioprocessingthread.cpp
src/src/audioprocessingthread.h
src/src/qtsingleapplication/qtsingleapplication.h

fix: 开源合规修改

---

src/src/majorimageprocessingthread.cpp

修复节能模式下相机卡顿问题
Log: 修复节能模式下相机卡顿问题
Bug: https://pms.uniontech.com/bug-view-154541.html

fix: 修复节能模式下相机卡顿问题

---

src/main.cpp

并行判断libavcodec
Bug: https://pms.uniontech.com/bug-view-173423.html
Log: 修复部分已知问题

fix: 修复无法录制MP4问题

---

src/CMakeLists.txt

project adaptation
Log: project adaptation

fix: project adaptation

---

src/main.cpp
src/src/Settings.cpp
src/src/basepub/datamanager.cpp
src/src/basepub/datamanager.h
src/src/videowidget.cpp

添加h264编码器检测，不存在时不支持mp4视频录制
Log: 添加h264编码器检测，不存在时不支持mp4视频录制

fix: 添加h264编码器检测，不存在时不支持mp4视频录制

---

src/src/videowidget.cpp

去除多余连接
Bug: https://pms.uniontech.com/bug-view-177273.html
Log: 修复部分已知问题

fix: 修复大窗口卡顿问题

---

src/src/imageitem.cpp

玲珑环境下通过dbus打开看图/影院预览
Log: 玲珑环境下通过dbus打开看图/影院预览
Bug: https://pms.uniontech.com/bug-view-148325.html
https://pms.uniontech.com/bug-view-158031.html

fix: 玲珑环境下通过dbus打开看图/影院

---

patches/remove-absolute-path-from-cmake-file.patch

fix: 玲珑打包失败

---

.tx/deepin.conf
debian/changelog

fix: 更新changlog

---

debian/changelog

new version 1.4.10
Log: modify changelog

chore: new version 1.4.10

---

src/src/mainwindow.cpp
src/src/rollingbox.cpp
src/src/titlebar.cpp
src/src/titlebar.h
src/src/videowidget.cpp
src/src/videowidget.h

修复主题切换相关bug
Log: 修复主题切换相关bug
Bug: https://pms.uniontech.com/bug-view-156737.html
https://pms.uniontech.com/bug-view-187173.html

fix: 修复主题切换相关bug

---

src/src/mainwindow.cpp

设置初始位置为标题栏
Bug: https://pms.uniontech.com/bug-view-120099.html
Log: 修复部分已知问题

fix: 修复焦点初始位置异常

---

src/main.cpp
src/src/Settings.cpp
src/src/basepub/datamanager.cpp
src/src/basepub/datamanager.h
src/src/mainwindow.cpp
src/src/rollingbox.cpp
src/src/titlebar.cpp
src/src/titlebar.h
src/src/videowidget.cpp
src/src/videowidget.h

合并release/eagle的修改到master
Log: 合并release/eagle的修改到master

chore: Merge branch 'release/eagle'

---

debian/changelog
debian/control
libcam/libcam_encoder/encoder.c
src/CMakeLists.txt
src/main.cpp
src/src/basepub/load_libs.c
src/src/basepub/load_libs.h

add vaapi encoder for h264
Log: add vaapi encoder for h264

chore: add vaapi encoder for h264

---

patches/remove-absolute-path-from-cmake-file.patch
src/CMakeLists.txt
src/src/imageitem.cpp
src/src/mainwindow.cpp
src/src/majorimageprocessingthread.cpp
tests/CMakeLists.txt

合并release/eagle上的修改到master;添加系统版本判断，兼容V20与V23
Log: merge branch 'release/eagle' to 'master'

fix: merge branch 'release/eagle' to 'master'

---

src/src/mainwindow.cpp

修复锁屏后快速解锁，相机崩溃问题
Log: 修复锁屏后快速解锁，相机崩溃问题
Bug: https://pms.uniontech.com/bug-view-198939.html

fix: 锁屏后快速解锁，相机崩溃

---

debian/changelog

New version 1.4.12
Log: new version 1.4.12

chore: new version 1.4.12

---

src/main.cpp
src/src/dbus_adpator.cpp
src/src/dbus_adpator.h

修复最小化后无法通过全局搜索唤醒
Log: 修复最小化后无法通过全局搜索唤醒
Bug: https://pms.uniontech.com/bug-view-200273.html

fix: 最小化后无法唤醒

---

debian/changelog

new version 1.4.13
Log: new version 1.4.13

fix: update changelog

---

debian/control
src/CMakeLists.txt
src/src/mainwindow.cpp
src/src/windowstatethread.cpp
src/src/windowstatethread.h
tests/CMakeLists.txt

通过kwayland接口获取wayland下窗口信息，当全屏覆盖相机时停止录像
Bug: https://pms.uniontech.com/bug-view-102292.html
Log: 修复部分已知问题

fix: 修复wayland下录像未停止问题

---

src/CMakeLists.txt

fix: 去除多余依赖

---

libcam/libcam_v4l2core/v4l2_core.c

fix: 修复安道大屏闪退问题

---

src/src/Settings.cpp
src/src/globalutils.cpp
src/src/globalutils.h
src/src/videowidget.cpp
src/src/windowstatethread.cpp

For some hardware, modify the default video format for recording to webm
Log: For some hardware, modify the default video format for recording to webm
Bug: https://pms.uniontech.com/bug-view-227831.html

fix: modify the default video format for recording to webm

---

debian/changelog

chore: tag 6.0.5

---

debian/changelog

chore: tag 6.0.6

---

src/assets/camera.conf
src/src/Settings.cpp
src/src/mainwindow.cpp

性能较差的设备上使用优先使用webm格式进行录制
Bug: https://pms.uniontech.com/bug-view-242517.html
Log: 修复部分已知问题

fix: 修复部分机器录制音视频不同步

---

debian/changelog

bump version
Log: bump version

chore: bump version 6.0.10

---

src/src/windowstatethread.cpp

Fix potential crashes
Log: Fix potential crashes

fix: Fix potential crashes

---

debian/control
src/src/imageitem.cpp

Remove Thumbnailer dependency
Log: Remove Thumbnailer dependency

fix: Remove Thumbnailer dependency

---

debian/control
src/src/imageitem.cpp

This reverts commit 0b8cd83efc186b30ee61d97e0c53e9ed6f4de738.

Revert "fix: Remove Thumbnailer dependency (#294)"

---

src/assets/org.deepin.camera.encode.json

fix the init encode config in PGUX
Log: fix the init encode config in PGUX
Bug: https://pms.uniontech.com/bug-view-254991.html

fix: the init encode config in PGUX

---

src/src/majorimageprocessingthread.cpp

Optimize preview efficiency
Log: Optimize preview efficiency

fix: Optimize preview efficiency

---

src/src/videowidget.cpp
src/src/videowidget.h

A distinction will be made between professional and community editions.
Log: the prefix file of save name incorrect
Bug: https://pms.uniontech.com/bug-view-255395.html

fix: the prefix file of save name incorrect

---

debian/changelog

bump version
Log: bump version

chore: bump version 6.0.11

---

src/CMakeLists.txt

Camera treeland adaptation
Log: Camera treeland adaptation

fix: Camera treeland adaptation

---

src/CMakeLists.txt
src/src/mainwindow.cpp
tests/CMakeLists.txt

Make build configuration files and dynamic library search more generic in order to adapt linglong build.
Log: Adapt to linglong.

chore: Adapt to linglong

---

arm64/linglong.yaml
debian/changelog
linglong.yaml

v6.5.1 release.
Log: v6.5.1 release.

chore: New version 6.5.1

---

src/src/devnummonitor.cpp

crash on the write_pipe
Log: 相机界面卡住
Bug: https://pms.uniontech.com/bug-view-283285.html

fix: 相机界面卡住

---

src/src/mainwindow.cpp

修复紧凑模式下按钮大小错误的问题
Log: 修复紧凑模式下按钮大小错误的问题
Bug: https://pms.uniontech.com/bug-view-279807.html

fix: 修复紧凑模式下按钮大小错误的问题

---

debian/changelog
src/src/mainwindow.cpp
src/src/mainwindow.h

修复紧凑模式的问题
Log: 修复紧凑模式适配问题
Bug: https://pms.uniontech.com/bug-view-279807.html

fix: 修复紧凑模式适配问题

---

src/src/videowidget.cpp
src/src/videowidget.h

screen flash during take photo
Log: screen flash when take photo
Bug: https://pms.uniontech.com/bug-view-285489.html

 fix: make screen flash stable during take photo

---

arm64/linglong.yaml
debian/changelog
linglong.yaml

Bump version to 6.5.6
Log: Bump version to 6.5.6

chore: Bump version to 6.5.6

---

src/src/imageitem.cpp

Use runtime OS edition instead of compilation
OS edition.
Log: Us runtime OS edition
Bug: https://pms.uniontech.com/bug-view-294085.html

fix: use runtime os edition

---

src/src/majorimageprocessingthread.cpp
src/src/videowidget.cpp

优化显示界面与原来不一致问题
Bug: https://pms.uniontech.com/bug-view-293127.html
Log: 优化显示界面

fix: 优化显示界面

---

libcam/libcam_encoder/encoder.c
src/CMakeLists.txt

check vaapi encoder fail
note wayland not support.(no device test)
Log: check vaapi encoder fail

fix: check vaapi encoder fail

---

src/configs/json/org_deepin_camera_encode.hpp

Add new configuration class for managing camera encoding settings
Log: add org_deepin_camera_encode configuration class

chore: add org_deepin_camera_encode configuration class

---

debian/control

chore: 去除错误依赖项

---

src/src/devnummonitor.cpp
src/src/imageitem.cpp
src/src/imageitem.h

Solve the problem of printing preview pictures too small and optimize the printing codes.
Log: Fix print preview issue.
Bug: https://pms.uniontech.com/bug-view-305457.html

fix: Fix print preview issue.

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml

Bump version to 6.5.14
Log: Bump version to 6.5.14

chore: Bump version to 6.5.14

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml

Bump version to 6.5.15
Log: Bump version to 6.5.15

chore: Bump version to 6.5.15

---

libcam/libcam_encoder/encoder.c
libcam/libcam_encoder/muxer.c

修复录制视频时卡住闪退
Bug: https://pms.uniontech.com//bug-view-307545.html
Log: 修复录制视频时卡住闪退

fix: 修复录制视频时卡住闪退

---

libcam/libcam_encoder/encoder.c

修复录制视频音视频不同步
Bug: https://pms.uniontech.com//bug-view-293127.html
Log: 修复录制视频音视频不同步

fix: 修复录制视频音视频不同步
