linuxdeepin/deepin-camera

src/src/videowidget.cpp
src/src/videowidget.h

Description: 解决x11下开启滤镜全屏连拍，左上角画面会闪烁的问题
Log: 解决x11下开启滤镜全屏连拍，左上角画面会闪烁的问题
Bug: https://pms.uniontech.com/bug-view-118753.html

fix: 解决x11下开启滤镜全屏连拍，左上角画面会闪烁的问题

---

src/src/gstvideowriter.cpp
src/src/gstvideowriter.h
src/src/majorimageprocessingthread.cpp
src/src/majorimageprocessingthread.h

Description: MIPS架构下，通过增加线程提升编码效率，降低录制帧率和成像质量，来减少视频录制所耗时间，避免出现视频时长不正确的情况
Log: MIPS架构使用gstreamer编码库，录制的视频时长不正确
Bug: https://pms.uniontech.com/bug-view-123491.html

fix: 解决MIPS架构使用gstreamer编码库，录制的视频时长不正确的问题

---

src/src/gstvideowriter.cpp
src/src/majorimageprocessingthread.cpp

Description: 调节滤镜/曝光后，rgb帧数据未分配内存，程序因访问空指针crash
Log: 解决滤镜/曝光调节，程序闪退的问题
Bug: https://pms.uniontech.com/bug-view-124535.html,https://pms.uniontech.com/bug-view-124537.html

fix: 解决滤镜/曝光调节，程序闪退的问题

---

libcam/libcam_encoder/mp4.c
src/src/imageitem.cpp

fix: 修复相机第二次录制无图像问题

---

src/src/majorimageprocessingthread.cpp
src/src/majorimageprocessingthread.h
src/src/videowidget.cpp

Modify the process and use the PTS as a time to display it
Bug: https://pms.uniontech.com/bug-view-134725.html,
https://pms.uniontech.com/bug-view-99224.html
Log: 修复部分已知问题

fix: The camera display is inconsistent with the recording time

---

src/src/windowstatethread.h

Fixes the following build failure on Arch, probably due to new compiler version:
```
/build/deepin-camera/src/deepin-camera-1.3.10/src/src/windowstatethread.cpp: In member function ‘virtual void windowStateThread::run()’:
/build/deepin-camera/src/deepin-camera-1.3.10/src/src/windowstatethread.cpp:45:27: error: ‘sleep_for’ is not a member of ‘std::this_thread’
45 |         std::this_thread::sleep_for(std::chrono::seconds(1));
|                           ^~~~~~~~~
```
Log: Fix build failure on Arch due to missing include

fix: build failure on Arch due to missing include

---

src/CMakeLists.txt

Log: Use as-needed to enhance compatibility with linker
relate: https://github.com/linuxdeepin/developer-center/issues/3345

fix: use as-needed instead of as-need

---

libcam/libcam_encoder/encoder.c
libcam/libcam_v4l2core/jpeg_decoder.c
libcam/libcam_v4l2core/uvc_h264.c
src/main.cpp
src/src/basepub/load_libs.c
src/src/basepub/load_libs.h

avcodec_get_context_defaults3 has been marked as deprecated since FFmpeg
4.0: https://ffmpeg.org/doxygen/4.0/group__lavc__core.html#ga1dd4bf43e6a4ec8b8d76bd3673e5e73a
Tested to be working fine on Arch with FFmpeg 5.1.
Log: Fix compatibility with FFmpeg 5

fix: compatibility with FFmpeg 5

---

src/main.cpp

通过正则表达式匹配libavcodec库文件
Log: 通过正则表达式匹配libavcodec库文件
Bug: https://pms.uniontech.com/bug-view-183421.html

fix: 修复默认视频格式不为mp4问题

---

src/src/imageitem.cpp

修复双击预览图会打开两个窗口问题
Log: 修复双击预览图会打开两个窗口问题
Bug: https://pms.uniontech.com/bug-view-161843.html

fix: 双击预览图片会打开两个窗口

---

src/src/mainwindow.cpp

修复wayland锁屏后拔插摄像头，解锁后点击录像按钮崩溃
Log: 修复wayland锁屏后拔插摄像头崩溃问题
Bug: https://pms.uniontech.com/bug-view-198571.html

fix: wayland锁屏后拔插摄像头崩溃问题

---

libcam/libcam_encoder/encoder.c

规避USB声卡端口状态正常，但无法获取音频数据时，点击结束录像崩溃问题
Log: 规避USB声卡端口状态正常，但无法获取音频数据时录像崩溃问题
Bug: https://pms.uniontech.com/bug-view-207319.html

fix: 修复USB声卡端口状态正常，但无法获取音频数据时录像崩溃问题

---

libcam/libcam_encoder/video_codecs.c

MP4录制出的视频内容少一到二秒的内容
Log: MP4录制出的视频内容少一到二秒的内容
Bug: https://pms.uniontech.com/bug-view-217973.html

fix: MP4录制出的视频内容少一到二秒的内容

---

debian/changelog

Bump version to 6.0.3
PR:
* https://github.com/linuxdeepin/deepin-camera/pull/242
* https://github.com/linuxdeepin/deepin-camera/pull/244
* https://github.com/linuxdeepin/deepin-camera/pull/246
* https://github.com/linuxdeepin/deepin-camera/pull/248
* https://github.com/linuxdeepin/deepin-camera/pull/263
* https://github.com/linuxdeepin/deepin-camera/pull/265
* https://github.com/linuxdeepin/deepin-camera/pull/266
Log: Bump version to 6.0.3
Issue: Bump version

chore: Bump version to 6.0.3

---

src/src/videowidget.cpp

修复打开相机时下方概率性出现静态图像的问题
Log: 修复打开相机时下方概率性出现静态图像的问题
Bug: https://pms.uniontech.com/bug-view-227191.html

fix: 打开相机下方概率性出现静态图

---

libcam/libcam/camview.c
libcam/libcam_encoder/encoder.c

修复高分辨率录像多次点击开始/结束导致崩溃问题，高分辨率录像时，编码线程释放时间较长，导致上一个线程还未释放完成，又创建了一个新的线程
Log: 修复高分辨率录像多次点击开始/结束导致崩溃问题
Bug: https://pms.uniontech.com/bug-view-228159.html

fix: 高分辨率录像多次点击开始/结束导致崩溃

---

debian/control

fix: remove unused dframeworkdbus from debian/control

---

libcam/libcam_encoder/encoder.c
libcam/libcam_v4l2core/jpeg_decoder.c
src/src/majorimageprocessingthread.cpp

修复v23 连上usb相机或自带相机笔记本启动相机时奔溃问题
Bug: https://pms.uniontech.com/bug-view-238775.html
Log: 更新ffmpeg版本后，修复v23 连上usb相机或自带相机笔记本启动相机时奔溃问题

fix: 修复v23 连上usb相机或自带相机笔记本启动相机时奔溃问题

---

src/CMakeLists.txt
src/assets/camera.conf
src/src/Settings.cpp
src/src/globalutils.cpp
src/src/globalutils.h
src/src/mainwindow.cpp
src/src/videowidget.cpp

For some hardware,such as CC GWMNDA1GL1 modify the default video format for recording to webm
Log: modify the default video format for recording to webm 2nd
Bug: https://pms.uniontech.com/bug-view-237059.html

fix: modify the default video format for recording to webm 2nd

---

src/main.cpp

应用涉及 GPU 加速，目前合成器重连暂未完整支持，
移除 QT_WAYLAND_RECONNECT 环境变量，不参与合成
器崩溃重连。
Log: 规避部分已知问题
Task: https://pms.uniontech.com/task-view-326583.html

feat: 不参与合成器崩溃重连

---

debian/changelog
debian/control

修复ffmpeg升级76后安装依赖报错
Log:  修复ffmpeg升级后安装依赖报错
Bug: https://pms.uniontech.com/bug-view-250209.html

fix: 修复ffmpeg升级后安装依赖报错

---

libcam/libcam_encoder/encoder.c

因ffmpeg从4升级5后API变动
Log:  修复拍摄视频出现闪退
Bug: https://pms.uniontech.com/bug-view-251245.html

fix:  修复拍摄视频出现闪退

---

libcam/libcam_encoder/encoder.c

Iris Xe Graphicsx图形处理器不支持vaapi, 导致相机录视频闪退
Log: Iris Xe Graphicsx图形处理器不支持vaapi, 导致相机录视频闪退
Bug: https://pms.uniontech.com/bug-view-256235.html

fix: Iris Xe Graphicsx图形处理器不支持vaapi, 导致相机录视频闪退

---

libcam/libcam/camview.c
libcam/libcam/camview.h
libcam/libcam_encoder/encoder.c
libcam/libcam_encoder/gviewencoder.h
src/CMakeLists.txt
src/assets/org.deepin.camera.encode.json
src/main.cpp

fix the omx encode cache small in PGUX
Log: fix the omx encode cache small in PGUX
Bug: https://pms.uniontech.com/bug-view-254991.html

fix: the omx encode cache small in PGUX

---

src/main.cpp

the correct get the product machine name
Log: the correct get the product machine name
Bug: https://pms.uniontech.com/bug-view-267231.html

fix: the correct get the product machine name

---

libcam/libcam_encoder/encoder.c

mask the 7d55 for encoder
Log: make the video record use softencode
Bug: https://pms.uniontech.com/bug-view-278369.html

fix: hardware encoder stash in 7d55

---

debian/changelog
src/main.cpp

remove kwayland-shell env
Log: remove kwayland-shell env

fix: remove kwayland-shell env

---

CMakeLists.txt
debian/control
src/CMakeLists.txt
src/src/windowstatethread.cpp
src/src/windowstatethread.h

Remove full screen occlusion and stop recording function
Log：Remove full screen occlusion and stop recording function 
Task: https://pms.uniontech.com/story-view-37517.html

fix: Remove full screen occlusion and stop recording function

---

libcam/libcam/camview.c
libcam/libcam/camview.h
src/assets/org.deepin.camera.encode.json
src/main.cpp
src/src/majorimageprocessingthread.cpp
src/src/previewopenglwidget.cpp

optimize delay for show
Log:  delay for show
Bug: https://pms.uniontech.com/bug-view-283415.html

fix: optimize delay for show

---

src/src/imageitem.cpp

Temporarily use ll-cli run deepin-movie, instead of DBus interface.
It seems that deepin-movie takes more time to start, causeing method calls to not respond.
Log: Fix start deepin-movie but not play.
Bug: https://pms.uniontech.com/bug-view-294085.html

fix: use ll-cli run deepin-movie

---

src/src/circlepushbutton.cpp
src/src/filterpreviewbutton.cpp
src/src/imageitem.cpp
src/src/photorecordbtn.cpp
src/src/videowidget.cpp

remove invalid  url
Log: remove invalid  url

fix: remove invalid  url

---

libcam/libcam_encoder/encoder.c
src/src/majorimageprocessingthread.cpp
src/src/previewopenglwidget.cpp
src/src/previewopenglwidget.h
src/src/videowidget.cpp

优化相机显示与录制卡顿回跳问题
Bug: https://pms.uniontech.com/bug-view-293127.html
Log: 优化相机显示与录制卡顿回跳问题

fix: 优化相机显示与录制卡顿回跳问题

---

src/src/videowidget.cpp

fix: 修复mips问题

---

libcam/libcam_v4l2core/v4l2_devices.c
src/src/devnummonitor.cpp

相机还原后查看设备信息
Bug: https://pms.uniontech.com/bug-view-292759.html
Log: 相机还原后查看设备信息

fix: 相机还原后查看设备信息

---

debian/control
debian/rules
src/CMakeLists.txt
src/main.cpp
src/src/Settings.cpp
src/src/camera.cpp
src/src/camera.h
src/src/circlepushbutton.cpp
src/src/circlepushbutton.h
src/src/closedialog.cpp
src/src/exposureslider.cpp
src/src/filterpreviewbutton.cpp
src/src/filterpreviewbutton.h
src/src/gstvideowriter.cpp
src/src/imageitem.cpp
src/src/mainwindow.cpp
src/src/photorecordbtn.cpp
src/src/photorecordbtn.h
src/src/previewopenglwidget.cpp
src/src/previewopenglwidget.h
src/src/rollingbox.cpp
src/src/switchcamerabtn.cpp
src/src/switchcamerabtn.h
src/src/takephotosettingareawidget.cpp
src/src/videowidget.cpp
src/src/videowidget.h

QT6 adaptation
Log: QT6 adaptation

feat: QT6 adaptation

---

src/com.deepin.Camera.service

Remove the commented shell command from com.deepin.Camera.service file as it's not needed for the service configuration and only served as a documentation artifact.
This cleanup improves code readability while maintaining the actual D-Bus service functionality.

refactor: remove unnecessary shell command from Camera service file

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml
src/translations/deepin-camera_lo.ts

- Changed package source URLs from testing25_daily to crimson_25.0 across all architectures (amd64, arm64, loong64).
- Updated corresponding file URLs and digests.
log: Update package URLs in linglong.yaml files

chore: Update package URLs in linglong.yaml files for all architectures
